# Generated by Django 5.0.6 on 2024-06-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='userName',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='main.usermodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='orders',
            field=models.ManyToManyField(related_name='user_orders', to='main.ordermodel'),
        ),
    ]
