# Generated by Django 5.0.6 on 2024-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ordermodel_username_ordermodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='user_orders', to='main.ordermodel'),
        ),
    ]
