# Generated by Django 5.0.6 on 2024-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usermodel_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
