# Generated by Django 5.0.6 on 2024-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ordermodel_description_alter_productmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
