# Generated by Django 5.0.6 on 2024-06-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categorymodel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='price',
        ),
    ]
