# Generated by Django 5.0.6 on 2024-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='productsList',
            field=models.ManyToManyField(related_name='order_product', to='main.productmodel'),
        ),
    ]
