# Generated by Django 5.0.6 on 2024-06-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_ordermodel_productslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
