# Generated by Django 4.2.13 on 2024-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='poster/')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
