# Generated by Django 4.2.13 on 2024-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_postermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='poster/'),
        ),
    ]
