# Generated by Django 5.0.7 on 2024-08-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_postermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
