# Generated by Django 5.0.7 on 2024-08-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_branchmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=30, null=True),
        ),
    ]
