# Generated by Django 5.0.7 on 2024-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_branchmodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
