# Generated by Django 5.0.7 on 2024-08-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_branchmodel_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.branchmodel'),
        ),
    ]
