# Generated by Django 5.0.7 on 2024-08-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_ordermodel_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='main.branchmodel'),
        ),
    ]
