# Generated by Django 5.0.7 on 2024-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_branchmodel_orderlist_alter_ordermodel_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmodel',
            name='orderList',
            field=models.ManyToManyField(blank=True, related_name='branch_orders', to='main.ordermodel'),
        ),
    ]
