# Generated by Django 5.0.7 on 2024-08-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_branchmodel_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmodel',
            name='orderList',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='branch',
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='productsList',
            field=models.ManyToManyField(related_name='order_product', to='main.productmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='main.usermodel'),
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='orders',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='user_orders', to='main.ordermodel'),
        ),
    ]
