# Generated by Django 5.0.7 on 2024-08-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_branchmodel_orderlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_price_9_6', models.IntegerField(default=0)),
                ('delivery_price_6_2', models.IntegerField(default=0)),
            ],
        ),
    ]
