# Generated by Django 5.0.7 on 2024-10-24 16:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_settingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone1', models.CharField(max_length=200)),
                ('phone2', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('instagram', models.CharField(blank=True, max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200)),
                ('youtube', models.CharField(blank=True, max_length=200)),
                ('whatsapp', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_card', models.CharField(max_length=200)),
                ('name_card', models.CharField(max_length=200)),
                ('cvv', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('accept', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('full_desc', models.TextField(blank=True)),
                ('mini_desc', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('job', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='upload')),
                ('qr', models.CharField(blank=True, max_length=400)),
                ('status', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='JoinToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iin', models.CharField(max_length=200)),
                ('date_birth', models.DateField(blank=True, default=datetime.date.today)),
                ('phone_number', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('child_navbars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.navbar')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('full_desc', models.TextField(blank=True)),
                ('mini_desc', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='media')),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('mini_desc', models.CharField(blank=True, max_length=200)),
                ('full_desc', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('longitude', models.CharField(blank=True, max_length=200)),
                ('latitude', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BranchModel',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='productsList',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='orders',
        ),
        migrations.DeleteModel(
            name='PosterModel',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='favoriteProducts',
        ),
        migrations.DeleteModel(
            name='SettingsModel',
        ),
        migrations.AddField(
            model_name='information',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.language'),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
