# Generated by Django 5.0.7 on 2024-10-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_category_contact_donate_information_jointogroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='language',
        ),
        migrations.RemoveField(
            model_name='information',
            name='language',
        ),
        migrations.RemoveField(
            model_name='navbar',
            name='language',
        ),
        migrations.RemoveField(
            model_name='news',
            name='language',
        ),
    ]
