# Generated by Django 5.0.7 on 2024-10-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_category_language_remove_contact_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='child_navbars',
        ),
    ]
