# Generated by Django 5.0.7 on 2024-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_navbar_child_navbars'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
