# Generated by Django 5.0.7 on 2024-10-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_famouspersonalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='famouspersonalities',
            name='buttons_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
