# Generated by Django 5.0.7 on 2024-10-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_famouspersonalities_buttons_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='child_navbars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.navbar'),
        ),
    ]
